version: "2.2"
services:
  db:
    container_name: db
    image: mysql:8.0.19
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: jhipster
    ports:
      - "3308:3306"
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      timeout: 20s
      retries: 10
  bugtrackerjhipster-app:
    build:
      context: ../
      dockerfile: Dockerfile-Back
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 8080:80
